(** Delays: the durations [d] of the computations [delay d], a monoid that each
    grade receives by a monoid morphism ({!Grade.S.of_delay}).

    The signatures are layered by what the grades built from delays need: a
    monoid ({!S}), a totally ordered one ({!ORDERED}), one with a truncated
    subtraction ({!MONUS}), one measured by the non-negative rationals
    ({!MEASURED}), and one generated by a single step ({!STEPPED}). The
    instances are the natural numbers ({!Nat}) and the non-negative rationals
    ({!Rational}). *)

(** Whether a list of witnesses decides the conditions it is given for. *)
type completeness =
  | Complete
      (** a condition in one rigid that holds at every witness holds at every
          value *)
  | Partial  (** a condition may hold at every witness and fail elsewhere *)

(** Monoids of delays, with their literals.

    Laws, [=] being {!equal}:
    - [add] is associative, with unit [zero]; it need not commute;
    - on the literals of non-negative rationals, [read] is a partial monoid
      morphism from [(ℚ≥0, +, 0)] whose domain is a submonoid: [read (Int 0)] is
      [Some zero], and if [read q = Some d] and [read r = Some e], then
      [read (q + r) = Some (add d e)]; [None] means that the delay is not
      expressible in the instance;
    - a rational literal of an integral value [n] reads as [Int n], and a
      negative literal as [None];
    - [equal d e] iff [compare d e = 0], and [hash] is compatible with [equal].
*)
module type S = sig
  type t
  (** The delays. *)

  val zero : t
  (** The delay [0], the unit of {!add}. *)

  val add : t -> t -> t
  (** The delay of [delay d; delay e] is [add d e]. *)

  val read : GradeLiteral.lit -> t option
  (** [read lit] is the delay the literal [lit] denotes, and [None] if it
      denotes none in this instance. *)

  val rejection : GradeLiteral.lit -> string
  (** [rejection lit] is the reason, for messages, that [read lit] is [None],
      e.g. ["delays are whole numbers of time steps"]. *)

  val equal : t -> t -> bool
  (** The equality of delays. *)

  val compare : t -> t -> int
  (** A total order on the representations of the delays, for data structures;
      not the order of {!ORDERED}. *)

  val hash : t -> int
  (** A hash compatible with {!equal}. *)

  val show : t -> string
  (** [show d] prints [d] as a literal that {!read} reads as [d]. *)

  val adjacent : lower:bool -> Rational.t -> Rational.t option
  (** [adjacent ~lower q] is, for a non-negative rational [q] that {!read}
      reads, the value of the least delay above [q] if [lower], and of the
      greatest delay below [q] otherwise, if there is one: [q + 1] and [q - 1]
      over whole time steps, and none over the rationals, which are dense. An
      open end of running-time bounds is the closed end it gives
      ({!Grade.close_running_time}). *)
end

(** Totally ordered monoids of delays, for time bounds and intervals.

    Laws, in addition to those of {!S}:
    - [leq] is a total preorder whose equivalence is [equal], and [add] is
      monotone in both arguments;
    - [zero] is least, and not greatest: the witnesses of any constants include
      a delay strictly above [zero];
    - [read] is monotone on the literals of rationals [q ≤ r] that it reads;
    - [min d e] and [max d e] are the lesser and the greater of [d] and [e]. *)
module type ORDERED = sig
  include S

  val leq : t -> t -> bool
  (** The order [≤] of the delays. *)

  val min : t -> t -> t
  (** [min d e] is the lesser of [d] and [e]. *)

  val max : t -> t -> t
  (** [max d e] is the greater of [d] and [e]. *)

  val witnesses : degree:int -> t list -> t list * completeness
  (** [witnesses ~degree cs] is a finite list of delays and its completeness:
      [Complete] if an ordering [L ≤ R] between expressions built from the
      delays [cs], a variable [j], sums and one of minima or maxima, each side
      with at most [degree] occurrences of [j], holds at every delay [j] iff it
      holds at every witness. *)
end

(** Ordered monoids of delays with a monus, a truncated subtraction: the
    commutative monoids with monus (Amer, Algebra Universalis 1984), totally
    ordered by their natural order.

    Laws, in addition to those of {!ORDERED}:
    - [add] is commutative;
    - residuation: [leq d (add e f) ⇔ leq (monus d e) f], so that [monus d e] is
      the least delay [f] with [d ≤ e + f];
    - the order is the natural one: if [leq e d], then [add e (monus d e) = d].

    Consequence: [monus d e = zero] iff [leq d e], by residuation at [f = zero].
*)
module type MONUS = sig
  include ORDERED

  val monus : t -> t -> t
  (** [monus d e] is the truncated difference [d ∸ e]: [zero] if [d ≤ e], and
      otherwise the delay that added to [e] gives [d]. *)
end

(** Ordered monoids of delays with a monus, measured by the non-negative
    rationals, which are also the running-time bounds of the operations.

    Laws, in addition to those of {!MONUS}:
    - [to_rational] is a monoid morphism into [(ℚ≥0, +, 0)] and an order
      embedding: [leq d e ⇔ to_rational d ≤ to_rational e];
    - [read (rational_lit (to_rational d)) = Some d]: [to_rational] is inverse
      to {!read}.

    Consequence: [to_rational (monus d e)] is [to_rational d - to_rational e]
    truncated at [0]. *)
module type MEASURED = sig
  include MONUS

  val to_rational : t -> Rational.t
  (** [to_rational d] is the non-negative rational the delay [d] measures, the
      value of the literals that {!read} reads as [d]. *)
end

(** Ordered monoids of delays generated by one time step, the delays being the
    numbers of time steps.

    Laws, in addition to those of {!MEASURED}:
    - [steps 0 = zero], [steps 1 = step] and
      [steps (m + n) = add (steps m) (steps n)]: [steps] is the monoid morphism
      from [(ℕ, +, 0)] sending [1] to [step];
    - [to_int (steps n) = n] for [n ≥ 0], and [steps (to_int d) = d]: [steps] is
      a bijection, with inverse [to_int];
    - [read] is defined exactly on the literals of the natural numbers, and
      [read (Int n) = Some (steps n)].

    Consequence: the order is that of the natural numbers,
    [leq d e ⇔ to_int d ≤ to_int e]; [steps] is an order isomorphism and [step]
    the least delay above [zero]. [leq d (add d e)] holds as [add] is monotone
    and [zero] least, and two delays mutually ordered are equal. *)
module type STEPPED = sig
  include MEASURED

  val step : t
  (** The delay of one time step. *)

  val steps : int -> t
  (** [steps n] is the delay of [n] time steps, the [n]-fold sum of {!step}.

      @raise Invalid_argument if [n] is negative. *)

  val to_int : t -> int
  (** [to_int d] is the number of time steps of [d]. *)
end

module Nat : STEPPED with type t = int
(** The natural numbers of time steps, written as integers. A fraction is
    rejected, as is an integer beyond [max_int]. The monus is the truncated
    subtraction of integers.

    The witnesses of the constants summing to [s] are [0], ..., [s+1], whatever
    the degree, and are complete. *)

module Rational : MEASURED with type t = Rational.t
(** The non-negative rationals, written as integers and fractions: decimals such
    as [1.5] or quotients such as [1/3]. A delay is printed as an integer, as a
    decimal if its expansion terminates, and otherwise as a quotient. The monus
    is the truncated subtraction of rationals, and a delay measures itself.

    Let [s] be the sum of the constants, [D] the least common multiple of their
    denominators, and [K ≥ 1] the degree. The witnesses are the grid
    [G = { x/(D·m) : x ∈ 0..s·D, m ∈ 1..K }], the midpoints of its consecutive
    elements and [s+1], and are complete. *)
