(cram
 (deps
  ../tempore
  (source_tree .)
  (source_tree ../examples/introduction)
  (source_tree ../examples/regular)
  (source_tree ../examples/regular_costs)
  (source_tree ../examples/time)
  (source_tree ../examples/rollout)
  (source_tree ../examples/sessions)
  (source_tree ../examples/traces)
  (source_tree ../examples/traces_costs)))
