(executable
 (name web)
 (libraries
  utils
  language
  vdom
  vdom.base
  ojs
  webBackend
  webInterpreter
  loader)
 (modes js)
 (link_flags -no-check-prims)
 (promote
  (until-clean)
  (into ../../../web)
  (only web.bc.js)))

;; This is an expanded form of the trick used in src/core/dune to generate the module
;; Examples_tpe with the examples to include in the web interface.

(rule
 (with-stdout-to
  examples_tpe.ml
  (progn
   (echo "let examples = [")
   ;; We need to repeat the following three lines for each included example.
   ;; The first line gives the name of the example and the name of the resource
   ;; grade it is meant to be run with (the web interface switches to that grade
   ;; when the example is loaded), and the second gives its source.
   (echo "({|Time: upper bounds|}, {|time-upper-bound|}, {|")
   (cat ../../../examples/time_upper.tpe)
   (echo "|});")
   (echo "({|Time: intervals|}, {|time-interval|}, {|")
   (cat ../../../examples/time_intervals.tpe)
   (echo "|});")
   (echo "({|Traces: lower bounds|}, {|traces-lower-bound|}, {|")
   (cat ../../../examples/traces_lower.tpe)
   (echo "|});")
   (echo "({|Traces: upper bounds|}, {|traces-upper-bound|}, {|")
   (cat ../../../examples/traces_upper.tpe)
   (echo "|});")
   (echo "({|Traces: intervals|}, {|traces-interval|}, {|")
   (cat ../../../examples/traces_intervals.tpe)
   (echo "|});")
   (echo "({|3D printing|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/3dprint.tpe)
   (echo "|});")
   (echo "({|3D printing with handlers|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/3dprint_handlers.tpe)
   (echo "|});")
   (echo "({|3D printing with traces|}, {|traces-interval|}, {|")
   (cat ../../../examples/3dprint_traces.tpe)
   (echo "|});")
   (echo "({|Eternal types|}, {|time-upper-bound|}, {|")
   (cat ../../../examples/eternal_types.tpe)
   (echo "|});")
   (echo "({|Basic temporal operations|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/delay.tpe)
   (echo "|});")
   (echo "({|Basic unbox|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/basic_unbox.tpe)
   (echo "|});")
   (echo "({|Folding over boxed values|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/fold_over_boxes.tpe)
   (echo "|});")
   (echo "({|Algebraic operations|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/operations.tpe)
   (echo "|});")
   (echo "({|Effect handlers: lower bounds|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/handlers_lower_bound.tpe)
   (echo "|});")
   (echo "({|Effect handlers: upper bounds|}, {|time-upper-bound|}, {|")
   (cat ../../../examples/handlers_upper_bound.tpe)
   (echo "|});")
   (echo "({|Effect handlers: nested|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/handlers_nested.tpe)
   (echo "|});")
   (echo "({|Effect handlers: nested (rejected)|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/handlers_nested_reject.tpe)
   (echo "|});")
   (echo "({|Top-level structures|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/toplevel.tpe)
   (echo "|});")
   (echo
    "({|Natural numbers as an inductive type|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/nat.tpe)
   (echo "|});")
   (echo "({|Recursive functions on integers|}, {|time-lower-bound|}, {|")
   (cat ../../../examples/recursion.tpe)
   (echo "|});")
   (echo "]"))))
